### ISSUE TITLE
Suggestion to use `command` to launch script at boot

### ISSUE THREAD

**Issue by antontkv** [wikiped/WSL-IpHandler#20]
Right now `/usr/local/bin/wsl-iphandler.sh` script runs every time when you open a new console. But really it only needed to be run at boot of the WSL2 VM.

You can use `command` [setting](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#boot-settings) in /etc/wsl.conf. Although it works only in Windows 11. Or you can create checks at the start of the script that will check if the settings already applied and exit.

**Comment by wikiped** [comment]
Thank you for the suggestion.

I am aware of the `command` setting, but as you noted it is for Win 11 only, therefore not an option.

Regarding:

  > create checks at the start of the script that will check if the settings already applied and exit

It is already implemented both for bash and pwsh. The powershell part is unfortunately the more annoying one since to check for the status of `hosts' file you have to execute powershell script, but it will not make any changes to the `hosts` file if the required record is already there.

I am open to suggestions on how this could be optimized without introducing another layer of complexity (like syncing some other config file with the actual state of `hosts` file).
