### ISSUE TITLE
vEthernet (WSL) is not created after the on-logon job execution

### ISSUE THREAD

**Issue by synclpz** [wikiped/Wsl-IpHandler#21]
I use static setup + on-logon scheduled task, which after reboot successfully completes (sometimes even calling out that WSL vSwitch had been already configured correctly) but no vEthernet (WSL) is seen via ipconfig. Then I start my WSL session and get default settings for vEthernet (something like 172.21.22... instead of static address I provided), so the WSL is set up with the address obviously not from required subnet and network is not working as expected.

The workaround I found it to delay scheduled task execution for 1 minute after logon.

**Comment by wikiped** [comment]
Thanks for reporting this observation.

It is difficult to guess what might be the exact reason for this behavior, but the thing is that if the module reports success - this means the adapter has been set up - because it's presence and actual parameters are validated after the the module tries to set it up.

The only thing I can think of is that adapter is being setup by mangling with Windows internals and I noticed that high level commands like `ipconfig` do NOT reflect the changes straight away and this delay depends on how busy the system is doing whatever it is doing or whatever the user has tasked it to do at the moment when the adapter was setup. I.e. the system needs some time to sync the changes in virtual devices state with it's internal representation of that state.

The delay you had set might be letting the module to run when the system is less busy and therefore the changes are reflected quicker (which might feel like immediately).

To validate this hypotheses you might try (without setting the delay manually) let the script do its job, and run `ipconfig` ___after___ some time (whatever time you found suitable for the delay).

 If the hypotheses holds true I might add an option to have the delay for the scheduled task script (i.e. with `-RunOnlyIfIdle` and `-IdleWaitTimeout` parameters).
