### ISSUE TITLE
Error during install `'Import-Psd' is not recognized`

### ISSUE THREAD

**Issue by antontkv** [wikiped/Wsl-IpHandler#32]
During installation I have this error on powershell 7.2.6:

```
Import-Psd: The term 'Import-Psd' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

But the module still loads and works as expected.

**Comment by wikiped** [comment]
Thanks for reporting this issue.

It is mostly non-breaking error caused by dependency on 3rd party module `PsdKit`. It is used here to read module version when checking for updates.

As a quick (and temporary) solution run `Install-Module PsdKit`

To resolve this - dependency will need to be removed, which I hope to make in the next few days.
