### ISSUE TITLE
Wsp-IpHandler vs WSP-IpHandler

### ISSUE THREAD

**Issue by roelarents** [wikiped/WSL-IpHandler#9]
It works, thank you!. But not before I used:
`Import-Module WSL-IpHandler` instead of:
`Import-Module Wsl-IpHandler` (note the capitals).

(Also I was running Powershell as Admin when it worked, but I didn't test non-admin and capitals.)

When it didn't work (for people googling) I received the following errors:

```
PowerShell installing WSL-IpHandler to Ubuntu...
[sudo] password for me:
Bash Installing WSL-IpHandler...
Bash Installed WSL-IpHandler!
PowerShell finished installation of WSL-IpHandler to Ubuntu with Errors:
Pinging windows from Ubuntu failed:
PING windows (<old ip>) 56(84) bytes of data.
From Ubuntu (172.16.0.2) icmp_seq=1 Destination Host Unreachable

--- windows ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
```

and
```
> Install-WslIpHandler Ubuntu -Verbose -Debug
PowerShell installing WSL-IpHandler to Ubuntu...
DEBUG: Get-PrivateData: PrivateData is null or -Force parameter has been set!
DEBUG: Get-PrivateData: Using $MyInvocation.MyCommand.Module: WSL-IpHandler
Get-PrivateData: C:\Users\me\Documents\PowerShell\Modules\Wsl-IpHandler\FunctionsPrivateData.ps1:49
Line |
  49 |      $local:ScriptNames = (Get-PrivateData $ModuleInfo)['ScriptNames']
     |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Value cannot be null. (Parameter 'ModuleInfo in Get-PrivateData does not have PrivateData!')
```

So I suggest a find/replace to consistently use the case-sensitive spelling of the module name everywhere including docs.

**Comment by wikiped** [comment]
Powershell is 'mostly' case insensitive so this must have been caused by something else.

The 'PrivateData' error has been appearing in one of the versions, but was fixed later. If you see this after updating to version 0.9.2 (current latest) please reopen this issue.

By the way, pressing <kbd>Tab</kbd> after `Import-Module wsl` saves from worrying about casing and spelling, assuming the module was installed as described on `README.md` page.
